version: '3.8'

services:
  postgres:
    image: localhost:5000/postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  redis:
    image: localhost:5000/redis:latest
    container_name: redis

  mongodb:
    image: localhost:5000/mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ati
      MONGO_INITDB_ROOT_PASSWORD: ati1234

  mongo-express:
    image: localhost:5000/mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ati
      ME_CONFIG_MONGODB_ADMINPASSWORD: ati1234
      ME_CONFIG_BASICAUTH_USERNAME: ati
      ME_CONFIG_BASICAUTH_PASSWORD: ati1234
    ports:
      - "8081:8081"  # Map internal port 8081 to host port 8081
    depends_on:
      - mongodb
